rvm:
  - 2.1
  - 2.2
env:
  - CHEF_DK_VERSION=0.10.0
  - CHEF_DK_VERSION=0.9.0

sudo: required

before_install: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk -v $CHEF_DK_VERSION
install: chef exec bundle install

script: chef exec rake travis
